resource_group_name      = "iw-accelerator-rg"
resource_prefix          = "iw-accelerator-test"
nginx_aca_name           = "nginx"
nginx_container_name     = "nginx"
backstage_aca_name       = "backstage"
backstage_container_name = "backstage"
