name: build
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment to deploy
        options:
          - dev
        default: dev

jobs:
  build:
    name: "Build ${{ github.event.inputs.environment }}"
    env:
      REPO_NAME: ${{ github.event.repository.name }}
      ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
      ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
      ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: '{"clientId": "${{ env.ARM_CLIENT_ID}}", "clientSecret":"${{env.ARM_CLIENT_SECRET}}", "tenantId": "${{ env.ARM_TENANT_ID}}","subscriptionId": "${{ env.ARM_SUBSCRIPTION_ID}}"}'


      - name: Install yarn
        run: |
          curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/yarn.gpg
          echo "deb [signed-by=/etc/apt/trusted.gpg.d/yarn.gpg] https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
          sudo apt update
          sudo apt install yarn

      - name: Install yarn dependencies
        working-directory: ./backstage
        run: |
          yarn install --frozen-lockfile
          yarn tsc

      - name: Build Application
        working-directory: ./backstage
        run: |
          # Build backend
          yarn build:backend --config ../../app-config.yaml

      - name: ACR build
        id: acr
        uses: azure/acr-build@v1
        with:
          service_principal: ${{ env.ARM_CLIENT_ID}}
          service_principal_password: ${{ env.ARM_CLIENT_SECRET}}
          tenant: ${{env.ARM_TENANT_ID}}
          registry: iwaccelerator.azurecr.io
          repository: ${{ secrets.repository }}
          image: "backstage-app-${{ github.event.inputs.environment }}"
          dockerfile: backstage/packages/backend/Dockerfile
          branch: main

      