name: deploy app
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment to deploy to
        options:
          - dev
          - prod
        default: dev

      destroy:
        type: boolean
        description: Destroy Terraform
        default: false
jobs:
  deploy:
    name: "Deploy ${{ github.event.inputs.environment }}"
    env:
      ENVIRONMENT: ${{ github.event.inputs.environment }}
      REPO_NAME: ${{ github.event.repository.name }}
      ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
      ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
      ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
      # Terraform variables
      TF_VAR_nginx_container_image_name: ${{ secrets.AZURE_REPO_URL }}/nginx:latest
      TF_VAR_backstage_container_image_name: ${{ secrets.AZURE_REPO_URL }}/iw-accelerator:latest
      TF_VAR_dns_zone_name: ${{secrets.DNS_ZONE_NAME}}
      TF_VAR_cname_record_name: ${{secrets.CNAME_RECORD_NAME}}
      TF_VAR_txt_record_name: ${{secrets.TXT_RECORD_NAME}}
      TF_VAR_dns_resource_group_name: ${{secrets.DNS_RESOURCE_GROUP_NAME}}
      TF_VAR_azure_tenant_id: ${{secrets.ARM_TENANT_ID}}
      TF_VAR_azure_auth_client_id: ${{secrets.AZURE_AUTH_CLIENT_ID}}
      TF_VAR_azure_auth_client_secret: ${{secrets.AZURE_AUTH_CLIENT_SECRET}}
      TF_VAR_postgres_host: '${{secrets.POSTGRES_HOST}}'
      TF_VAR_postgres_user: ${{secrets.POSTGRES_USER}}
      TF_VAR_postgres_password: ${{secrets.POSTGRES_PASSWORD}}
      

    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            terraform

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: '{"clientId": "${{ env.ARM_CLIENT_ID}}", "clientSecret":"${{env.ARM_CLIENT_SECRET}}", "tenantId": "${{ env.ARM_TENANT_ID}}","subscriptionId": "${{ env.ARM_SUBSCRIPTION_ID}}"}'

      - name: Get Backend Storage Key
        run: export ARM_ACCESS_KEY=$(az storage account keys list --resource-group backstage-terraform --account-name iwterraformstate --query '[0].value' -o tsv)

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./terraform
        run: |
          terraform init -backend-config="key=${{ env.REPO_NAME }}-${{ env.ENVIRONMENT }}.tfstate"

      - name: Terraform Validate
        working-directory: ./terraform
        run: |
          terraform validate

      - name: Terraform Plan
        if: github.event.inputs.destroy == 'false'
        working-directory: ./terraform
        id: plan
        run: |
          terraform plan  -var-file="./tfvars/${{ github.event.inputs.environment }}-vars.tfvars" -out main.tfplan

      - name: Apply
        if: github.event.inputs.destroy == 'false'
        working-directory: ./terraform
        run: |
          terraform apply "main.tfplan"

      - name: Terraform Destroy
        if: github.event.inputs.destroy == 'true'
        working-directory: ./terraform
        run: |
          terraform destroy -auto-approve -var-file="./tfvars/${{ github.event.inputs.environment }}-vars.tfvars"
